blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions
    url: https://github.com/TwoHearts-AI/template_repository/discussions
    about: Please ask and answer questions here.
  - name: Security Vulnerability
    url: https://github.com/TwoHearts-AI/template_repository/security/policy
    about: Please report security vulnerabilities following our security policy.
